version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out s3://demo-todo-list/ --delete
      - aws cloudfront create-invalidation --distribution-id E1KUL9GTC88I6D --paths "/*"
artifacts:
  base-directory: ./out
  files:
    - '**/*'
  discard-paths: no
