name: CI/CD for build and deploy
on:
  push:
    branches:
      - deploy/gitops
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 22.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 22.17.0	
      - run: npm ci
  build:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.17.0]
    steps:
        - uses: actions/checkout@v3
        - name: Use node ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3.12
      - name: Get secrets from AWS Secrets Manager
        run: |
          # Retrieve secrets and export as environment variables
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "gitops-deploy-secret" --query SecretString --output text)
          
          # Parse JSON and export individual secrets
          echo "AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r '.AWS_ACCESS_KEY_ID')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.AWS_SECRET_ACCESS_KEY')" >> $GITHUB_ENV
          echo "AWS_BUCKET_NAME=$(echo $SECRET_JSON | jq -r '.AWS_BUCKET_NAME')" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION_ID=$(echo $SECRET_JSON | jq -r '.AWS_CLOUDFRONT_DISTRIBUTION_ID')" >> $GITHUB_ENV     
      - name: Config AWS Cred
        run: |
          pip install awscli
          aws configure set region us-east-1
          aws configure set output json
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy with S3 sync and Invalidate CloudFront cache
        run: |
          npm ci
          npm run build
          aws s3 sync ./out s3://${{ env.AWS_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
